WINDOW_SIZE                 = (840, 440)

USER_SELECTING_RADUIS       = 10

BUTTON_ICON_SIZE            = 32
CONSTRAINT_ICON_SIZE        = 20
CONSTRAINT_ICON_SPACING     = 25
LINE_TICKNESS               = 3
POINT_RADIUS                = 4
TEXT_BOTTOM_OFFSET          = 15
TEXT_SIDE_OFFSET            = 15
MENU_TOP_OFFSET             = 10
MENU_SIDE_OFFSET            = 10

EXTENSION_LINE_LENGTH       = 40
DIMENSION_LINE_OFFSET       = 30
EXTENSION_LINE_THICKNESS    = 1